DOC: Frontend documentation
SE-TINF22B2/G6-SimpleQ pull request #159
Opened 2024-05-16 20:45 UTC by Integraluminium

Readme for developers to help them setup the project

2024-05-17 15:07 UTC, Jozys requested changes
Two little issues that needs to be addressed, than this PR can be merged.

2024-05-18 19:47 UTC, benniloidl commented on frontend/src/components/CircularProgress.tsx
> + * Renders animated circular progress that goes from 0 deg (0%) to 180 deg (100%) and renders the percentage in between
No because it is only a half circle.

2024-05-19 11:34 UTC, Jozys commented on frontend/src/components/CircularProgress.tsx
> + * Renders animated circular progress that goes from 0 deg (0%) to 180 deg (100%) and renders the percentage in between
Okay, than everything here is fine.

2024-05-20 19:57 UTC, benniloidl approved these changes

2024-05-20 20:05 UTC, Jozys approved these changes
Looks good now.

2024-05-20 20:06 UTC, merged