FE: API, Code Cleanup & Fixes
SE-TINF22B2/G6-SimpleQ pull request #222
Opened 2024-06-06 08:44 UTC by benniloidl

2024-06-06 16:03 UTC, Jozys commented
Please provide a description of what you changed in this PR.

2024-06-06 22:24 UTC, Integraluminium requested changes
I think there are many changes, which are a bit confusing to look at.
Please check license for the pictures and export for i18n.

_Have you tested usability on firefox?_

2024-06-06 22:29 UTC, benniloidl commented on frontend/src/components/avatar/Avatar.tsx
> +					currentTarget.src = "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50";
Yes

2024-06-06 22:50 UTC, benniloidl commented
The requests have been implemented (even though they did not regard the changes in this PR).

2024-06-07 09:08 UTC, Integraluminium commented
Looks good for me,
+ Internal server error is fixed in #227 due to errors in backend
+ The button to post answers is missing, please fix in next PR
+ I18n is provided partly, please move on and extract more elements into the language file

2024-06-07 09:10 UTC, Integraluminium approved these changes
Please review last comment

2024-06-08 07:05 UTC, merged